spring:
  profiles: default
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/
---
spring:
  profiles: replica
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/