---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AravindSh/E-Commerce-POC
          searchPaths: ConfigFiles
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh